[profile.default]
libs = ['lib']
out = 'out'
remappings = [
  'ds-test/=lib/ds-test/src/',
  '@openzeppelin/=node_modules/@openzeppelin/',
  '@blockswaplab/=node_modules/@blockswaplab',
  'hardhat/=node_modules/hardhat/',
]
solc_version = '0.8.13'
src = 'contracts'

# See more config options https://github.com/gakonst/foundry/tree/master/config
block_number = 120000 
block_timestamp = 1640000000 
gas_limit = 9223372036854775807 # the gas limit in tests

[fuzz]
max_test_rejects = 1000000